spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7b2072.p.ssafy.io:3306/token?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: B207
    password: B207user!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  redis:
    host: k7b2072.p.ssafy.io
    port: 6379

  OAuth2:
    google:
      url : https://accounts.google.com/o/oauth2/v2/auth
      client-id : 772414000810-4sp08rireoj3p28fvpklud1cf142vcbg.apps.googleusercontent.com
      client-secret : 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
      callback-url : https://k7b2071.p.ssafy.io/auth-service/login/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

token:
  access_token:
    # 12시간
    expiration_time: 43200000
  refresh_token:
    # 7일
    expiration_time: 604800000
  secret: secretKey
  refresh: refreshKey
