server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://j7b305.p.ssafy.io:8761/eureka
      defaultZone: http://localhost:8761/eureka

spring:
  # bean중복 에러 해결
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
#  zipkin:
#    # TODO : 서버에 Open Zipkin Jar 파일 다운로드 후 실행하면 연결됨
#    base-url: http://j7b305.p.ssafy.io:9411
#    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            #- RemoveRequestHeader=Cookie
            #- RewritePath=/user-service/(?<segment>.*),/$\{segment}
        ##---------------------------------------------USER FILTER START---------------------------------------------------------------
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            #- RemoveRequestHeader=Cookie
            #- RewritePath=/user-service/(?<segment>.*),/$\{segment}
        #---------------------------------------------USER FILTER END---------------------------------------------------------------

        #---------------------------------------------ISSUE FILTER START---------------------------------------------------------------
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival
        #            - Method=POST,PUT
        #          filters:
        #            - AdminFilter
        #
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival/**
        #            - Method=DELETE
        #          filters:
        #            - AdminFilter
        #
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival-form
        #            - Method=GET
        #          filters:
        #            - AdminFilter
        #
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival-form/**
        #            - Method=GET
        #          filters:
        #            - AdminFilter
        #
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival-form
        #            - Method=POST,PUT
        #          filters:
        #            - AuthorizationFilter
        #
        #        - id: festival-service
        #          uri: lb://FESTIVAL-SERVICE
        #          predicates:
        #            - Path=/api/festival-service/festival-form/**
        #            - Method=DELETE
        #          filters:
        #            - AuthorizationFilter

        - id: issue-service
          uri: lb://ISSUE-SERVICE
          predicates:
            - Path=/api/issue-service/**
            - Method=GET,POST,PUT,DELETE
        #---------------------------------------------ISSUE FILTER END---------------------------------------------------------------

        #---------------------------------------------MAIN FILTER START---------------------------------------------------------------
        #        - id: main-service
        #          uri: lb://MAIN-SERVICE
        #          predicates:
        #            - Path=/api/main-service/category
        #            - Method=POST
        #          filters:
        #            - AdminFilter
        #
        #        - id: main-service
        #          uri: lb://MAIN-SERVICE
        #          predicates:
        #            - Path=/api/main-service/question
        #            - Method=POST
        #          filters:
        #            - AdminFilter

        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/api/main-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - AuthorizationFilter
        #---------------------------------------------MAIN FILTER END---------------------------------------------------------------

        #---------------------------------------------RECOMM FILTER START---------------------------------------------------------------
        - id: recomm-service
          uri: lb://RECOMM-SERVICE
          predicates:
            - Path=/api/recomm-service/**
            - Method=GET,POST
#          filters:
#            - AuthorizationFilter
#---------------------------------------------RECOMM FILTER END---------------------------------------------------------------

token:
  secret: secretKey
  refresh: refreshKey
